pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/voa2000/DevOps.git'

                // Run Maven on a Unix agent.
                sh "docker ps"
                sh " cd ../terraform"
                sh "ls -lts"

                // To run Maven on a Windows agent, use
                // bat "mvn -Dmaven.test.failure.ignore=true clean package"
            }

        }
    }
}