pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/voa2000/DevOps.git'
            }

        }

        stage('Terraform init') {
            steps {
                sh "cd terraform"
                sh "terraform init"
                sh "ls -lts"
            }

        }

        stage('Plan') {
            steps {
                sh "terraform plan"
            }

        }
    }
}