pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Get some code from a GitHub repository
                    dir('DevOps') {
        git url: 'https://github.com/voa2000/DevOps.git'
    }

    sh('ls -lts')
    sh('pwd')

            }

        }

        stage('Terraform init') {
            steps {
                sh "pwd"
                sh "cd DevOps/terraform/."
                sh "pwd"
                sh "terraform init"
                sh "ls -lts"
            }

        }

        stage('Plan') {
            steps {
                sh "terraform plan"
            }

        }
    }
}